# Generated by Django 5.2.17 on 2026-08-07 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('uploading', 'Uploading'), ('extracting', 'Reading pages'), ('analysing', 'Analysing figures'), ('indexing', 'Building index'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('error', models.TextField(blank=True, default='')),
                ('stage_detail', models.CharField(blank=True, default='', max_length=120)),
                ('pages_total', models.PositiveIntegerField(default=0)),
                ('pages_done', models.PositiveIntegerField(default=0)),
                ('num_chunks', models.PositiveIntegerField(default=0)),
                ('num_figures', models.PositiveIntegerField(default=0)),
                ('sha256', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('size_bytes', models.BigIntegerField(default=0)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('is_scanned', models.BooleanField(default=False)),
                ('has_signatures', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Figure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('kind', models.CharField(choices=[('signature', 'Signature'), ('stamp_or_seal', 'Stamp or seal'), ('chart', 'Chart'), ('diagram', 'Diagram'), ('flowchart', 'Flowchart'), ('table_image', 'Table image'), ('photo', 'Photo'), ('screenshot', 'Screenshot'), ('logo', 'Logo'), ('letterhead', 'Letterhead'), ('handwriting', 'Handwriting'), ('formula', 'Formula'), ('map', 'Map'), ('floor_plan', 'Floor plan'), ('id_document', 'ID document'), ('barcode_or_qr', 'Barcode or QR'), ('image', 'Image'), ('other', 'Other')], default='other', max_length=24)),
                ('image', models.ImageField(blank=True, null=True, upload_to='figures/')),
                ('caption', models.TextField(blank=True, default='')),
                ('ocr_text', models.TextField(blank=True, default='')),
                ('labels', models.JSONField(blank=True, default=list)),
                ('has_signature', models.BooleanField(default=False)),
                ('has_stamp', models.BooleanField(default=False)),
                ('is_decorative', models.BooleanField(default=False)),
                ('confidence', models.FloatField(default=0.0)),
                ('analysed_by', models.CharField(default='heuristics', max_length=16)),
                ('x0', models.FloatField(default=0)),
                ('y0', models.FloatField(default=0)),
                ('x1', models.FloatField(default=0)),
                ('y1', models.FloatField(default=0)),
                ('source', models.CharField(default='raster', max_length=8)),
                ('sha1', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='figures', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'page_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('text', models.TextField()),
                ('kind', models.CharField(choices=[('text', 'Text'), ('figure', 'Figure')], default='text', max_length=8)),
                ('page_number', models.PositiveIntegerField(blank=True, null=True)),
                ('page_end', models.PositiveIntegerField(blank=True, null=True)),
                ('token_estimate', models.PositiveIntegerField(default=0)),
                ('embedding', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.document')),
                ('figure', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='documents.figure')),
            ],
            options={
                'ordering': ['document_id', 'index'],
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField()),
                ('text', models.TextField(blank=True, default='')),
                ('width', models.FloatField(default=0)),
                ('height', models.FloatField(default=0)),
                ('has_text_layer', models.BooleanField(default=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='documents.document')),
            ],
            options={
                'ordering': ['document_id', 'number'],
            },
        ),
        migrations.CreateModel(
            name='UploadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('filename', models.CharField(max_length=255)),
                ('total_size', models.BigIntegerField(default=0)),
                ('total_parts', models.PositiveIntegerField(default=0)),
                ('received_parts', models.JSONField(blank=True, default=list)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upload_session', to='documents.document')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['owner', 'status'], name='documents_d_owner_i_683479_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['document', 'page_number'], name='documents_f_documen_b518af_idx'),
        ),
        migrations.AddIndex(
            model_name='figure',
            index=models.Index(fields=['document', 'kind'], name='documents_f_documen_983044_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['document', 'kind'], name='documents_c_documen_66fe45_idx'),
        ),
        migrations.AddIndex(
            model_name='chunk',
            index=models.Index(fields=['document', 'page_number'], name='documents_c_documen_b9f390_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='chunk',
            unique_together={('document', 'index')},
        ),
        migrations.AddIndex(
            model_name='page',
            index=models.Index(fields=['document', 'number'], name='documents_p_documen_ccfaa9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='page',
            unique_together={('document', 'number')},
        ),
    ]
