# Generated by Django 5.2.17 on 2026-08-07 04:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='resumes/')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('parsing', 'Parsing'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('raw_text', models.TextField(blank=True, default='')),
                ('sections', models.JSONField(blank=True, default=dict)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('format_report', models.JSONField(blank=True, default=dict)),
                ('base_score', models.JSONField(blank=True, default=dict)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('word_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Tailoring',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(blank=True, default='', max_length=255)),
                ('company', models.CharField(blank=True, default='', max_length=255)),
                ('job_description', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('working', 'Working'), ('ready', 'Ready'), ('failed', 'Failed')], default='pending', max_length=12)),
                ('error', models.TextField(blank=True, default='')),
                ('requirements', models.JSONField(blank=True, default=dict)),
                ('gap_analysis', models.JSONField(blank=True, default=dict)),
                ('before_score', models.JSONField(blank=True, default=dict)),
                ('after_score', models.JSONField(blank=True, default=dict)),
                ('tailored', models.JSONField(blank=True, default=dict)),
                ('change_log', models.JSONField(blank=True, default=list)),
                ('docx_file', models.FileField(blank=True, null=True, upload_to='tailored/')),
                ('txt_file', models.FileField(blank=True, null=True, upload_to='tailored/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailorings', to=settings.AUTH_USER_MODEL)),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tailorings', to='resume.resume')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
