# Generated by Django 5.2.17 on 2026-08-07 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tailoring',
            name='answers',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='evidence',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='fabrication',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='pdf_file',
            field=models.FileField(blank=True, null=True, upload_to='tailored/'),
        ),
        migrations.AddField(
            model_name='tailoring',
            name='questions',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
